### ISSUE TITLE
SwaggerFilters Annotation don't work at the Method level 

### ISSUE THREAD

**Issue by bspradling** [paradoxical-io/paradoxical.io#2]
I would love to be able to use annotation at the method level to exclude a specific endpoint in Swagger. 

My specific use case is: 
SwaggerFilter.withAnnotation(classAnnotation).withoutAnnotation(methodAnnotation). 

This way, the filter will select all the endpoints within a specific class but exclude certain methods within that class. 

As I see it right now, it will only work with Annotations on the class level, which is very unfortunate. :(

**Comment by jakeswenson** [comment]
Please file this on the appropriate repo in paradoxical-io/dropwizard.swagger. Thanks!
